//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

class NodeosSwigModulePINVOKE
{

    protected class SWIGExceptionHelper
    {

        public delegate void ExceptionDelegate(string message);
        public delegate void ExceptionArgumentDelegate(string message, string paramName);

        static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
        static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
        static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
        static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
        static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
        static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
        static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
        static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
        static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
        static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
        static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

        static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
        static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
        static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

        [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "SWIGRegisterExceptionCallbacks_NodeosSwigModule")]
        public static extern void SWIGRegisterExceptionCallbacks_NodeosSwigModule(
                                    ExceptionDelegate applicationDelegate,
                                    ExceptionDelegate arithmeticDelegate,
                                    ExceptionDelegate divideByZeroDelegate,
                                    ExceptionDelegate indexOutOfRangeDelegate,
                                    ExceptionDelegate invalidCastDelegate,
                                    ExceptionDelegate invalidOperationDelegate,
                                    ExceptionDelegate ioDelegate,
                                    ExceptionDelegate nullReferenceDelegate,
                                    ExceptionDelegate outOfMemoryDelegate,
                                    ExceptionDelegate overflowDelegate,
                                    ExceptionDelegate systemExceptionDelegate);

        [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "SWIGRegisterExceptionArgumentCallbacks_NodeosSwigModule")]
        public static extern void SWIGRegisterExceptionCallbacksArgument_NodeosSwigModule(
                                    ExceptionArgumentDelegate argumentDelegate,
                                    ExceptionArgumentDelegate argumentNullDelegate,
                                    ExceptionArgumentDelegate argumentOutOfRangeDelegate);

        static void SetPendingApplicationException(string message)
        {
            SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
        }
        static void SetPendingArithmeticException(string message)
        {
            SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
        }
        static void SetPendingDivideByZeroException(string message)
        {
            SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
        }
        static void SetPendingIndexOutOfRangeException(string message)
        {
            SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
        }
        static void SetPendingInvalidCastException(string message)
        {
            SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
        }
        static void SetPendingInvalidOperationException(string message)
        {
            SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
        }
        static void SetPendingIOException(string message)
        {
            SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
        }
        static void SetPendingNullReferenceException(string message)
        {
            SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
        }
        static void SetPendingOutOfMemoryException(string message)
        {
            SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
        }
        static void SetPendingOverflowException(string message)
        {
            SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
        }
        static void SetPendingSystemException(string message)
        {
            SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
        }

        static void SetPendingArgumentException(string message, string paramName)
        {
            SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
        }
        static void SetPendingArgumentNullException(string message, string paramName)
        {
            global::System.Exception e = SWIGPendingException.Retrieve();
            if (e != null) message = message + " Inner Exception: " + e.Message;
            SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
        }
        static void SetPendingArgumentOutOfRangeException(string message, string paramName)
        {
            global::System.Exception e = SWIGPendingException.Retrieve();
            if (e != null) message = message + " Inner Exception: " + e.Message;
            SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
        }

        static SWIGExceptionHelper()
        {
            SWIGRegisterExceptionCallbacks_NodeosSwigModule(
                                      applicationDelegate,
                                      arithmeticDelegate,
                                      divideByZeroDelegate,
                                      indexOutOfRangeDelegate,
                                      invalidCastDelegate,
                                      invalidOperationDelegate,
                                      ioDelegate,
                                      nullReferenceDelegate,
                                      outOfMemoryDelegate,
                                      overflowDelegate,
                                      systemDelegate);

            SWIGRegisterExceptionCallbacksArgument_NodeosSwigModule(
                                      argumentDelegate,
                                      argumentNullDelegate,
                                      argumentOutOfRangeDelegate);
        }
    }

    protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

    public class SWIGPendingException
    {
        [global::System.ThreadStatic]
        private static global::System.Exception pendingException = null;
        private static int numExceptionsPending = 0;
        private static global::System.Object exceptionsLock = null;

        public static bool Pending
        {
            get
            {
                bool pending = false;
                if (numExceptionsPending > 0)
                    if (pendingException != null)
                        pending = true;
                return pending;
            }
        }

        public static void Set(global::System.Exception e)
        {
            if (pendingException != null)
                throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
            pendingException = e;
            lock (exceptionsLock)
            {
                numExceptionsPending++;
            }
        }

        public static global::System.Exception Retrieve()
        {
            global::System.Exception e = null;
            if (numExceptionsPending > 0)
            {
                if (pendingException != null)
                {
                    e = pendingException;
                    pendingException = null;
                    lock (exceptionsLock)
                    {
                        numExceptionsPending--;
                    }
                }
            }
            return e;
        }

        static SWIGPendingException()
        {
            exceptionsLock = new global::System.Object();
        }
    }


    protected class SWIGStringHelper
    {

        public delegate string SWIGStringDelegate(string message);
        static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

        [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "SWIGRegisterStringCallback_NodeosSwigModule")]
        public static extern void SWIGRegisterStringCallback_NodeosSwigModule(SWIGStringDelegate stringDelegate);

        static string CreateString(string cString)
        {
            return cString;
        }

        static SWIGStringHelper()
        {
            SWIGRegisterStringCallback_NodeosSwigModule(stringDelegate);
        }
    }

    static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


    static NodeosSwigModulePINVOKE()
    {
    }

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_delete_SwigLoggerBase")]
    public static extern void delete_SwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_deep_mind_version")]
    public static extern void SwigLoggerBase_on_deep_mind_version(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, uint jarg3, uint jarg4);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_deep_mind_versionSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_deep_mind_versionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, uint jarg3, uint jarg4);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_abidump_start")]
    public static extern void SwigLoggerBase_on_abidump_start(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_abidump_startSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_abidump_startSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_abidump_abi")]
    public static extern void SwigLoggerBase_on_abidump_abi(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_abidump_abiSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_abidump_abiSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_abidump_end")]
    public static extern void SwigLoggerBase_on_abidump_end(global::System.Runtime.InteropServices.HandleRef jarg1);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_abidump_endSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_abidump_endSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_start_block")]
    public static extern void SwigLoggerBase_on_start_block(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_start_blockSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_start_blockSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_accepted_block")]
    public static extern void SwigLoggerBase_on_accepted_block(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_accepted_blockSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_accepted_blockSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_switch_forks")]
    public static extern void SwigLoggerBase_on_switch_forks(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_switch_forksSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_switch_forksSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_error")]
    public static extern void SwigLoggerBase_on_error(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_errorSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_errorSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_onblock")]
    public static extern void SwigLoggerBase_on_onblock(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_onblockSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_onblockSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_applied_transaction")]
    public static extern void SwigLoggerBase_on_applied_transaction(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_applied_transactionSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_applied_transactionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_add_ram_correction")]
    public static extern void SwigLoggerBase_on_add_ram_correction(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, string jarg4, ulong jarg5, ulong jarg6);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_add_ram_correctionSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_add_ram_correctionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, string jarg4, ulong jarg5, ulong jarg6);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_input_action")]
    public static extern void SwigLoggerBase_on_input_action(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_input_actionSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_input_actionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_require_recipient")]
    public static extern void SwigLoggerBase_on_require_recipient(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_require_recipientSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_require_recipientSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_send_inline")]
    public static extern void SwigLoggerBase_on_send_inline(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_send_inlineSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_send_inlineSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_send_context_free_inline")]
    public static extern void SwigLoggerBase_on_send_context_free_inline(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_send_context_free_inlineSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_send_context_free_inlineSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_cancel_deferred")]
    public static extern void SwigLoggerBase_on_cancel_deferred(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, uint jarg3, ulong jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, ulong jarg6, uint jarg7, uint jarg8, uint jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_cancel_deferredSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_cancel_deferredSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, uint jarg3, ulong jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, ulong jarg6, uint jarg7, uint jarg8, uint jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_send_deferred")]
    public static extern void SwigLoggerBase_on_send_deferred(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, uint jarg3, ulong jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, ulong jarg6, uint jarg7, uint jarg8, uint jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_send_deferredSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_send_deferredSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, uint jarg3, ulong jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, ulong jarg6, uint jarg7, uint jarg8, uint jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_create_deferred")]
    public static extern void SwigLoggerBase_on_create_deferred(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, uint jarg3, ulong jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, ulong jarg6, uint jarg7, uint jarg8, uint jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_create_deferredSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_create_deferredSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, uint jarg3, ulong jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, ulong jarg6, uint jarg7, uint jarg8, uint jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_fail_deferred")]
    public static extern void SwigLoggerBase_on_fail_deferred(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_fail_deferredSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_fail_deferredSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_create_table")]
    public static extern void SwigLoggerBase_on_create_table(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_create_tableSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_create_tableSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_remove_table")]
    public static extern void SwigLoggerBase_on_remove_table(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_remove_tableSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_remove_tableSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_db_store_i64")]
    public static extern void SwigLoggerBase_on_db_store_i64(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6, ulong jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_db_store_i64SwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_db_store_i64SwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6, ulong jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_db_update_i64")]
    public static extern void SwigLoggerBase_on_db_update_i64(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6, ulong jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_db_update_i64SwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_db_update_i64SwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6, ulong jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_db_remove_i64")]
    public static extern void SwigLoggerBase_on_db_remove_i64(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6, ulong jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_db_remove_i64SwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_db_remove_i64SwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6, ulong jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_ram_event")]
    public static extern void SwigLoggerBase_on_ram_event(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, string jarg3, string jarg4, string jarg5, string jarg6, ulong jarg7, ulong jarg8, long jarg9);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_ram_eventSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_ram_eventSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, string jarg3, string jarg4, string jarg5, string jarg6, ulong jarg7, ulong jarg8, long jarg9);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_create_permission")]
    public static extern void SwigLoggerBase_on_create_permission(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_create_permissionSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_create_permissionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_modify_permission")]
    public static extern void SwigLoggerBase_on_modify_permission(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_modify_permissionSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_modify_permissionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_remove_permission")]
    public static extern void SwigLoggerBase_on_remove_permission(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_on_remove_permissionSwigExplicitSwigLoggerBase")]
    public static extern void SwigLoggerBase_on_remove_permissionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_new_SwigLoggerBase")]
    public static extern global::System.IntPtr new_SwigLoggerBase();

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_SwigLoggerBase_director_connect")]
    public static extern void SwigLoggerBase_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, SwigLoggerBase.SwigDelegateSwigLoggerBase_0 delegate0, SwigLoggerBase.SwigDelegateSwigLoggerBase_1 delegate1, SwigLoggerBase.SwigDelegateSwigLoggerBase_2 delegate2, SwigLoggerBase.SwigDelegateSwigLoggerBase_3 delegate3, SwigLoggerBase.SwigDelegateSwigLoggerBase_4 delegate4, SwigLoggerBase.SwigDelegateSwigLoggerBase_5 delegate5, SwigLoggerBase.SwigDelegateSwigLoggerBase_6 delegate6, SwigLoggerBase.SwigDelegateSwigLoggerBase_7 delegate7, SwigLoggerBase.SwigDelegateSwigLoggerBase_8 delegate8, SwigLoggerBase.SwigDelegateSwigLoggerBase_9 delegate9, SwigLoggerBase.SwigDelegateSwigLoggerBase_10 delegate10, SwigLoggerBase.SwigDelegateSwigLoggerBase_11 delegate11, SwigLoggerBase.SwigDelegateSwigLoggerBase_12 delegate12, SwigLoggerBase.SwigDelegateSwigLoggerBase_13 delegate13, SwigLoggerBase.SwigDelegateSwigLoggerBase_14 delegate14, SwigLoggerBase.SwigDelegateSwigLoggerBase_15 delegate15, SwigLoggerBase.SwigDelegateSwigLoggerBase_16 delegate16, SwigLoggerBase.SwigDelegateSwigLoggerBase_17 delegate17, SwigLoggerBase.SwigDelegateSwigLoggerBase_18 delegate18, SwigLoggerBase.SwigDelegateSwigLoggerBase_19 delegate19, SwigLoggerBase.SwigDelegateSwigLoggerBase_20 delegate20, SwigLoggerBase.SwigDelegateSwigLoggerBase_21 delegate21, SwigLoggerBase.SwigDelegateSwigLoggerBase_22 delegate22, SwigLoggerBase.SwigDelegateSwigLoggerBase_23 delegate23, SwigLoggerBase.SwigDelegateSwigLoggerBase_24 delegate24, SwigLoggerBase.SwigDelegateSwigLoggerBase_25 delegate25, SwigLoggerBase.SwigDelegateSwigLoggerBase_26 delegate26, SwigLoggerBase.SwigDelegateSwigLoggerBase_27 delegate27);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_Clear")]
    public static extern void StringVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_Add")]
    public static extern void StringVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_size")]
    public static extern uint StringVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_capacity")]
    public static extern uint StringVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_reserve")]
    public static extern void StringVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_new_StringVector__SWIG_0")]
    public static extern global::System.IntPtr new_StringVector__SWIG_0();

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_new_StringVector__SWIG_1")]
    public static extern global::System.IntPtr new_StringVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_new_StringVector__SWIG_2")]
    public static extern global::System.IntPtr new_StringVector__SWIG_2(int jarg1);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_getitemcopy")]
    public static extern string StringVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_getitem")]
    public static extern string StringVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_setitem")]
    public static extern void StringVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_AddRange")]
    public static extern void StringVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_GetRange")]
    public static extern global::System.IntPtr StringVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_Insert")]
    public static extern void StringVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_InsertRange")]
    public static extern void StringVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_RemoveAt")]
    public static extern void StringVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_RemoveRange")]
    public static extern void StringVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_Repeat")]
    public static extern global::System.IntPtr StringVector_Repeat(string jarg1, int jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_Reverse__SWIG_0")]
    public static extern void StringVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_Reverse__SWIG_1")]
    public static extern void StringVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_SetRange")]
    public static extern void StringVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_Contains")]
    public static extern bool StringVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_IndexOf")]
    public static extern int StringVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_LastIndexOf")]
    public static extern int StringVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_StringVector_Remove")]
    public static extern bool StringVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_delete_StringVector")]
    public static extern void delete_StringVector(global::System.Runtime.InteropServices.HandleRef jarg1);

    [UnmanagedCallConv(CallConvs = new Type[] { typeof(CallConvStdcall), typeof(CallConvSuppressGCTransition) })]
    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_NodeosSwig_Start",CallingConvention = CallingConvention.StdCall)]
    public static extern int NodeosSwig_Start(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_new_NodeosSwig")]
    public static extern global::System.IntPtr new_NodeosSwig();

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint = "CSharp_delete_NodeosSwig")]
    public static extern void delete_NodeosSwig(global::System.Runtime.InteropServices.HandleRef jarg1);
}
