//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System.Runtime.InteropServices;


[StructLayout(LayoutKind.Sequential)]
public struct SwigDataWrapper
{
    public volatile IntPtr Data;
    public volatile int Size;
}
